### ISSUE TITLE
Upstream problems when docker-compose build from a remote context

### ISSUE THREAD

**Issue by freol35241** [chalmers-revere/opendlv-video-x264-recorder#1]
FYI, ran in to the following problem when trying to use this according to the example docker-compose setup in the readme:

https://github.com/docker/compose/issues/8309

It manifests itself by complaining like this when doing docker-compose up:
```
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEIQZFg0S/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
: exit status 128
```

The current working solution is to downgrade the docker-compose version.

**Comment by chrberger** [comment]
Updated Dockerfile and Dockerfile.amd64 to fix outdated SSL certificates
